--- #YAML:1.0
name: Filter-Include
version: 1.4
license: perl
distribution_type: module
requires:
  Filter::Simple: '>= 0.70'
  Module::Locate: '>= 0.1'
  Regexp::Common: '>= 0.01'
  perl: 5.6.1
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Filter::Include:
    file: lib/Filter/Include.pm
    version: 1.4
generated_by: Module::Build version 0.19
